### ISSUE TITLE
Can't import this theme

### ISSUE THREAD

**Issue by Fasteroid** [stillgbx/synthwave-vs#1]
Downloaded the repo, but attempting to import for VS2019 yields the following error:
![image](https://user-images.githubusercontent.com/29342750/119241321-9439d680-bb23-11eb-806d-371f256c4c58.png)
What am I doing wrong?  I'm new to Visual Studio and can find almost nothing online about how to install themes.

**Comment by Fasteroid** [comment]
I solved the problem; apparently changing line 2 of the .vstheme file to `  <Theme Name="synthwave" GUID="{8ce01fb1-0081-4502-bda5-d6b0c613726f}">` fixes the issue.  It still throws an error, but imports successfully,

**Comment by stillgbx** [comment]
Readme updated for setup instructions (VS 2019 & 2022).
